import axios from "axios";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage<{ profile: any }> = ({ profile }) => {
  console.log(profile);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello, World {profile}</main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    const response = await axios.get(
      "http://localhost:3000/authentication/test",
      {
        headers: {
          ...(context.req?.headers as any),
        },
      }
    );
    if (response && response.status === 200) {
      return { props: { profile: response.data } };
    }
  } catch (error) {
    console.error(error);
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    props: { profile: {} },
  };
};
